name = "serp-collector"
type = "webpack"
zone_id = ""
account_id = "99be8d895486e3b8f947d996b06e2592"
route = ""
workers_dev = true
compatibility_date = "2021-12-02"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
