name = "serp-collector"
type = "javascript"
zone_id = ""
account_id = "99be8d895486e3b8f947d996b06e2592"
route = ""
workers_dev = true
compatibility_date = "2021-12-02"

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./worker.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

[vars]
GOOGLE_CLOUD_PROJECT = "rank-tracker-alliance"
BACKBLAZE_BUCKET_ID = "2c34dab355808d2975d10c17"
BACKBLAZE_APP_ID = "002c4a350d951c70000000001"
